"""
Centralized configuration constants for LightRAG.

This module defines default values for configuration constants used across
different parts of the LightRAG system. Centralizing these values ensures
consistency and makes maintenance easier.
"""

# Default values for environment variables
DEFAULT_MAX_GLEANING = 1
DEFAULT_FORCE_LLM_SUMMARY_ON_MERGE = 4
DEFAULT_WOKERS = 2
DEFAULT_TIMEOUT = 150

# Query and retrieval configuration defaults
DEFAULT_TOP_K = 40
DEFAULT_CHUNK_TOP_K = 10
DEFAULT_MAX_ENTITY_TOKENS = 10000
DEFAULT_MAX_RELATION_TOKENS = 10000
DEFAULT_MAX_TOTAL_TOKENS = 32000
DEFAULT_HISTORY_TURNS = 0
DEFAULT_ENABLE_RERANK = True
DEFAULT_COSINE_THRESHOLD = 0.2
DEFAULT_RELATED_CHUNK_NUMBER = 10

# Separator for graph fields
GRAPH_FIELD_SEP = "<SEP>"

# Logging configuration defaults
DEFAULT_LOG_MAX_BYTES = 10485760  # Default 10MB
DEFAULT_LOG_BACKUP_COUNT = 5  # Default 5 backups
DEFAULT_LOG_FILENAME = "lightrag.log"  # Default log filename

# Multi-model configuration environment variable names
# Task-specific LLM model configurations
ENTITY_EXTRACTION_LLM_BINDING = "ENTITY_EXTRACTION_LLM_BINDING"
ENTITY_EXTRACTION_LLM_MODEL = "ENTITY_EXTRACTION_LLM_MODEL"
ENTITY_EXTRACTION_LLM_BINDING_HOST = "ENTITY_EXTRACTION_LLM_BINDING_HOST"
ENTITY_EXTRACTION_LLM_BINDING_API_KEY = "ENTITY_EXTRACTION_LLM_BINDING_API_KEY"
ENTITY_EXTRACTION_LLM_KWARGS = "ENTITY_EXTRACTION_LLM_KWARGS"

ENTITY_SUMMARY_LLM_BINDING = "ENTITY_SUMMARY_LLM_BINDING"
ENTITY_SUMMARY_LLM_MODEL = "ENTITY_SUMMARY_LLM_MODEL"
ENTITY_SUMMARY_LLM_BINDING_HOST = "ENTITY_SUMMARY_LLM_BINDING_HOST"
ENTITY_SUMMARY_LLM_BINDING_API_KEY = "ENTITY_SUMMARY_LLM_BINDING_API_KEY"
ENTITY_SUMMARY_LLM_KWARGS = "ENTITY_SUMMARY_LLM_KWARGS"

RELATION_SUMMARY_LLM_BINDING = "RELATION_SUMMARY_LLM_BINDING"
RELATION_SUMMARY_LLM_MODEL = "RELATION_SUMMARY_LLM_MODEL"
RELATION_SUMMARY_LLM_BINDING_HOST = "RELATION_SUMMARY_LLM_BINDING_HOST"
RELATION_SUMMARY_LLM_BINDING_API_KEY = "RELATION_SUMMARY_LLM_BINDING_API_KEY"
RELATION_SUMMARY_LLM_KWARGS = "RELATION_SUMMARY_LLM_KWARGS"

QUERY_LLM_BINDING = "QUERY_LLM_BINDING"
QUERY_LLM_MODEL = "QUERY_LLM_MODEL"
QUERY_LLM_BINDING_HOST = "QUERY_LLM_BINDING_HOST"
QUERY_LLM_BINDING_API_KEY = "QUERY_LLM_BINDING_API_KEY"
QUERY_LLM_KWARGS = "QUERY_LLM_KWARGS"

KEYWORD_EXTRACTION_LLM_BINDING = "KEYWORD_EXTRACTION_LLM_BINDING"
KEYWORD_EXTRACTION_LLM_MODEL = "KEYWORD_EXTRACTION_LLM_MODEL"
KEYWORD_EXTRACTION_LLM_BINDING_HOST = "KEYWORD_EXTRACTION_LLM_BINDING_HOST"
KEYWORD_EXTRACTION_LLM_BINDING_API_KEY = "KEYWORD_EXTRACTION_LLM_BINDING_API_KEY"
KEYWORD_EXTRACTION_LLM_KWARGS = "KEYWORD_EXTRACTION_LLM_KWARGS"

# Task type identifiers
TASK_ENTITY_EXTRACTION = "entity_extraction"
TASK_ENTITY_SUMMARY = "entity_summary"
TASK_RELATION_SUMMARY = "relation_summary"
TASK_QUERY_RESPONSE = "query_response"
TASK_KEYWORD_EXTRACTION = "keyword_extraction"
